### ISSUE TITLE
Issues with creating local dev

### ISSUE THREAD

**Issue by borlak** [LandOfTheRair/landoftherair#1054]
npm install worked
npm setup errored out, the original command:
`npm run task:seed && npm run task:macros && && npm run autogenerated && npm run `prebuild:prod
has two sets of &&, when I changed it to:
`npm run task:seed && npm run task:macros && npm run autogenerated && npm run prebuild:prod`
it ran okay.  however, it then errored at:

> fs.js:646
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
> 

with the error:

> Error: ENOENT: no such file or directory, open '/root/landoftherair/scripts/../src/client/assets/spritesheets/creatures.png'
>     at Object.fs.openSync (fs.js:646:18)
>     at Function.md5FileSync [as sync] (/root/landoftherair/node_modules/md5-file/index.js:10:15)
>     at files.forEach.file (/root/landoftherair/scripts/prebuild-client.js:11:23)
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/root/landoftherair/scripts/prebuild-client.js:10:7)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)

if you can't include your production spritesheets for legal reasons, maybe at least a placeholder?

**Comment by seiyria** [comment]
They should be installed when you do `npm install` (they are installed as part of the `postinstall`, see [here](https://github.com/LandOfTheRair/landoftherair/blob/master/package.json#L30)). If for whatever reason they aren't being installed (which I'll fix as best as I can), they are located [here](https://github.com/LandOfTheRair/assets-built), so you can download them manually. Not that you should have to, of course!

**Comment by seiyria** [comment]
As a resolution for this, I've adjusted `npm run setup` to also run `postinstall` which will always get the assets (https://github.com/LandOfTheRair/landoftherair/commit/b427150c095fcdd9611afcead3238aed6892a07d). Sorry for this!
