### ISSUE TITLE
Party exp is unrestricted

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#157]
Brought second character to Selen, was able to pick up the kill quest, party members level 1 and 15, both got full exp and credit for the kill quest

**Comment by sarimash** [comment]
If this is intended that's cool, but it wasn't super hard to keep the alt alive even mostly naked

**Comment by seiyria** [comment]
do you mean they both got XP for turning in the quest?

**Comment by seiyria** [comment]
Xp should be cut by 50% if the level difference between bottom and top is 5 or more. If it's 10 or more, 75%, 20 90% and 30 99%

**Comment by sarimash** [comment]
difference between bottom and top, or difference between this character and top? is the high level punished for having a low level in party?

**Comment by seiyria** [comment]
I was thinking bottom and top so it's entirely the same for everyone in the party.

**Comment by seiyria** [comment]
I was thinking bottom and top so it's entirely the same for everyone in the party.

**Comment by sarimash** [comment]
Hmmmm, bottom and top... I can't immediately think of a way to get around that, other than having a ladder of powerleveling characters every 8 levels or so. Levels, say, 10 and 15 fighting together in Tower seems easy enough to ignore, but later game I could see levels 34 and 39 hunting on the same cata floor together which would make the party cut significant.

**Comment by seiyria** [comment]
closed by 8d379ee133187958fd829720e3c77571156aa05d
