### ISSUE TITLE
Buffs granted from two pieces of gear get removed with the first item

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#166]
Equip two items that have the same Autocast effect
Take one off, and you lose the buff while still wearing the other

Found this testing the new Newbie bracers, before that it only affected the (currently un-obtainable) Frost Chakram:
![image](https://user-images.githubusercontent.com/6930354/116798402-fbccab00-aabc-11eb-949b-069f80f9f5b7.png)

**Comment by seiyria** [comment]
closed by 7270584efbd873802ed7ad3d3823518a8879bb13
