### ISSUE TITLE
Identical spell potions aren't stacking

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#168]
These potions are from the vendor and splitting out into separate items
![image](https://user-images.githubusercontent.com/6930354/116825831-ec9e3980-ab5e-11eb-8e5e-8f7656dc2a49.png)

**Comment by sarimash** [comment]
Looks like this is because 'ounces' is stored as a mod, so Bottles are never considered "unmodified"

Maybe it makes sense to let non-tying items that have identical mods stack, or add a special exception for the "ounces" modifier. Just checked and this does also apply to foods, are there any other items that always have a mod that would need an exception?

**Comment by seiyria** [comment]
I wouldn't want to add an exception for ounces, because then it would stack and get eaten if there was something that had, say 10oz dropped onto a 1oz. the extra tracking might be a bit much.

my approach would be to not set ounces on mods until the first drink has happened

**Comment by seiyria** [comment]
Given that items now track how much you bought them for, I think this might not happen for a while.
