### ISSUE TITLE
New players that are somehow offline are currently visible in game?

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#169]
Hopefully the changes to account handling fix this, but wanted to post this as an initial data point in case it keeps popping up after today fix goes in. I went to the healer these two guys are recalled to, I can't remember if I logged them off at the healer.
![image](https://user-images.githubusercontent.com/6930354/116826701-53255680-ab63-11eb-957d-64dbcfd59e49.png)

their accounts are showing as not in game:
![image](https://user-images.githubusercontent.com/6930354/116826714-6506f980-ab63-11eb-82ba-a27f39cbf1f2.png)

Logging each account in fixed them (and they logged in at the healer)

Now that I think about it, maybe they were just left in game after logging out, died, wrenched to healer and regenned to full. That's more likely than my logging them out at the healer...

**Comment by seiyria** [comment]
I hope this is fixed now with some recent changes.
