### ISSUE TITLE
Dragging sometimes highlights the map, making it uninteractive

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#176]
Screenshot: 
![image](https://user-images.githubusercontent.com/6930354/116942752-33b02b80-ac40-11eb-87d3-b47bcc6dd2b1.png)

Low priority because there's an easy way to fix it (drag any item) but it could still be annoying to people who don't know that.

**Comment by seiyria** [comment]
shouldn't be a problem anymore w/ the upgrade to rxjs 7.x, but if it comes up at least there's prior art
