### ISSUE TITLE
Suggest downloading the client somewhere on the game page

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#177]

**Comment by sarimash** [comment]
https://rair.land/download

**Comment by seiyria** [comment]
This will need to check if the app is currently running in electron or not and conditionally show the download button, probably in the menu as a top level item: https://github.com/electron/electron/issues/2288

**Comment by seiyria** [comment]
![image](https://user-images.githubusercontent.com/763609/117323123-3be0b480-ae54-11eb-97c1-4dd3feb6c431.png)

might need to be more forward but this is a good spot for now
