### ISSUE TITLE
fake walls reveal themselves sometimes via shadows

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#198]
![image](https://user-images.githubusercontent.com/6930354/117208746-76e6d780-adc3-11eb-8abb-cd8b6e96b2fb.png)

that hole is a fake wall you should need truesight to see. this is not consistent though, I took the screenshot then it fixed itself without my even moving

**Comment by seiyria** [comment]
needs a repro unfortunately.
