### ISSUE TITLE
You've Got Mail (?)

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/landoftherair#20]
Possibly, it would be nice to be able to send mail to other players with items/gold in game.

Possibly, this could take the place of trading #18 

You'd talk to an NPC in a town and he'd let you check your mail.

**Comment by cjepson1978** [comment]
Mail exchange would likely (and has proven to) dominate the common needs for peer to peer trading.  But peer to peer trading should still be implemented in cases where 1) access to mailboxes could prove difficult or 2) the needs for trading interactions are time sensitive. 

An alternative approach would be to treat the mailing system as a carrier pigeon. This would allow a user's carried item (or UI interface) to act as a mail service requests. Further, like FORM/DROP SOCCUR limitations found in DRAKKAR's Nork -7, a mail service request could be suspended where appropriate.

**Comment by seiyria** [comment]
I think I like the idea of a mailbox that you can check in town, but you can send mail from "anywhere" (with limitations described above). For urgent trading, they could just drop-trade items (or there could be a similar `trade enable` command).

**Comment by seiyria** [comment]
Problem: how do you notify a user they have mail when they're in a different room, without them having to log back in?

**Comment by seiyria** [comment]
Nah. This causes too many concerns with things like: "how do you write a command to send mail" and etc. The only way this would work is if you hold the scroll in right, and one item in left, but then you can only send one item, which is no good.
