### ISSUE TITLE
Refresh option on desktop client

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#214]
Ideally just let the asset mismatch error be clickable to reload the page? might require clearing cache too?

 When I get this error on the desktop client I have to close the client out and relaunch it
![image](https://user-images.githubusercontent.com/6930354/117516628-9f0f3b80-af67-11eb-98e3-661f54e70994.png)

**Comment by seiyria** [comment]
I just confirmed via a local test that in future updates, if you click on this error, it'll go away.

Let me know if that's not the case in the future.
