### ISSUE TITLE
FurUpgrader balancing

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#226]
I'll put in the tying/requirements merging in a few minutes, but other questions are popping up:

1. What all slots should be paddable? Currently it's just checking if the item can be upgraded, so I believe all items can be padded. Might make sense to limit to some subset of armor/robes/cloaks/helm/boots, with the extra caveat that monks use boots as an offensive slot and allowing a purely defensive bonus in that slot feels almost like an extra nerf to tiger stance

2. In rair 1, padding explicitly stripped just the protections off a piece of gear to use for the padding, while currently it's adding the entire item in the slot. If the number of slots that can be padded is severely limited this should be fine (we're not effectively wearing 6 base armors at a time) but things like AC30 from abom could get out of hand (and would basically require tuning the late game around everyone having that padded)

**Comment by seiyria** [comment]
1. At most, armor and helm I think for now. If more slots need to be opened up, we can cross that bridge.

2. It should probably only take resists, not AC. basically, what I would (or will) do is to check if the stat has `Resist` and if so, it works. That's a logical next change.
