### ISSUE TITLE
Dexed to new map, npcs not showing after revive

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#268]
Sarimash killed Revhellfire and took him to Padili, after rezzing in the room Padili's character icon is not showing (but he shows on the entities sidebar)
![image](https://user-images.githubusercontent.com/6930354/120119711-40547080-c167-11eb-97b6-6f922585a90d.png)

**Comment by seiyria** [comment]
managed to repro this again; will investigate
