### ISSUE TITLE
generated modifiers for Experienced/Skilled misleading

### ISSUE THREAD

**Issue by sarimash** [LandOfTheRair/LandOfTheRair#350]
**Describe the bug**
The modifiers for Experienced/Skilled are 0.05 percent instead of 5 percent. See screenshots in Screenshots section.

**To Reproduce**
1. Check data in Dev tools/ discordGlobalCharacter
2. Equip 'Experienced' or 'Skilled' gear from Ori/Solo
3. Check discordGlobalCharacter again

**Expected behavior**
The value on the gear should be significant and match the value shown in the tooltip

**Screenshots**
![itemdesc](https://user-images.githubusercontent.com/6930354/191378392-af09fa66-97f2-482f-8a79-573e761f7b58.png)
Naked: 
![naked](https://user-images.githubusercontent.com/6930354/191378404-129f7bb7-0c30-444a-a3fe-3001e54c8996.PNG)
Wearing ori gear: 
![origear](https://user-images.githubusercontent.com/6930354/191378416-8d8c1333-7ca0-4a51-a38f-6d9fb8973e22.PNG)
Wearing one OWTS piece:
![owts](https://user-images.githubusercontent.com/6930354/191378436-c0028944-48c1-43da-b391-dd1deeb01439.PNG)
Wearing one OWTS piece and one ori piece:
![origear](https://user-images.githubusercontent.com/6930354/191378461-50bac7fd-a236-414b-aca7-ebad392ce213.PNG)

**Platform (please complete the following information):**
 - Platform web
 - Browser chrome

**Additional context**
This one was slightly difficult to tell if it was intentional or a bug; given that the tooltip says percent and that these are the entire features of the gear, and that the gear specifically spawns without an upgrade slot, I would expect them to be significantly better than owts. Aside from that, 0.1% experience/skill gain is negligible and completely unuseful.

**Comment by seiyria** [comment]
0.05 is 5%, that should be correct. whether it's negligible or not is hard to say; having it on every gear slot isn't bad per se, but it's an option. please close this if I am right, but you might have to do some research on the math. I'm more inclined to believe the owts gear is wrong (?) but you'll need to check the implementation.

**Comment by sarimash** [comment]
The implementation divides your (Stat.XPBoostPercent) by 100:
![xpformula](https://user-images.githubusercontent.com/6930354/191386735-7f7a4f54-9e4a-44f3-8a5a-47df359b3c82.PNG)
Same with skill:
![skill](https://user-images.githubusercontent.com/6930354/191386780-80c1ccc8-15ce-40ce-9cb6-7902140e2fd3.PNG)
Related, the food and ori/solokar ingots are also set up as decimals:
![image](https://user-images.githubusercontent.com/6930354/191386852-88bc8f21-3dc6-4ff8-85e4-1f0239d92adc.png)
![image](https://user-images.githubusercontent.com/6930354/191386880-b3b61407-1f20-4015-912f-dd351feedf89.png)

**Comment by seiyria** [comment]
It sounds like the numbers need to be changed then, at least. I guess that changed somewhere along the way.
