### ISSUE TITLE
[Bug] - eagle eye buff broken 

### ISSUE THREAD

**Issue by jwb2j** [LandOfTheRair/LandOfTheRair#401]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the bug

Eagle eye buff is supposed to let you see items hidden in trees and water hexes - it does not 

used to give accuracy buff not sure if removal was intentional 

### Expected behavior

Eagle eye buff is supposed to let you see items hidden in trees and water hexes - it does not 

used to give accuracy buff not sure if removal was intentional 

### Current behavior

Eagle eye buff is supposed to let you see items hidden in trees and water hexes - it does not 

used to give accuracy buff not sure if removal was intentional 

### To Reproduce

Cast the buff 

### Platform

Desktop

**Comment by seiyria** [comment]
It is not supposed to give an accuracy buff, as far as I can tell.
