### ISSUE TITLE
[Bug] - minotaur flask timer doesnt count down

### ISSUE THREAD

**Issue by jwb2j** [LandOfTheRair/LandOfTheRair#402]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the bug

Minotaur horn flask buff timer does show it counting down properly 

### Expected behavior

Count time at the same rate as other buffs 

### Current behavior

Does not seem to tick down consistently, after hours of play buff timer still shows 9574 of 10k and does not count down 

### To Reproduce

Drink flask and watch buff timers 

### Platform

Desktop

**Comment by seiyria** [comment]
If you're referring to the VitalEssence buff, it's a barrier, not a timer. So it only ticks down when you take damage.
