### ISSUE TITLE
[Content] - NPCs using summons

### ISSUE THREAD

**Issue by jwb2j** [LandOfTheRair/LandOfTheRair#406]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the content change

These present no risk to players and can be upgraded or removed to save resources 

### Is your change request related to an existing issue? Please describe.

No

### Describe alternatives you've considered or encountered

Upgrade the spell for npcs so that the summons are equivalent to npcs in their area

**Comment by seiyria** [comment]
I think they should be better at using their summons now. But let me know!
