### ISSUE TITLE
Need GUI Sprite Sheet

### ISSUE THREAD

**Issue by cjepson1978** [LandOfTheRair/landoftherair#87]
Updated

**Comment by seiyria** [comment]
Seems okay so far, but I'm not seeing the buttons for ok, next, cancel, etc.

For frames, I think the window title should definitely be above the window, not in it - no window was designed with that in mind. There would need to be an extra border to make that work.

What are the hand slots compared to other things here?

**Comment by cjepson1978** [comment]
Buttons are not ready for preview. 
Noted: Title art separate from window frame; include extra boarders. 
KOD (Kingdom of Drakkar) uses hand art in game to represent what users are holding in-hand (e.g., which hand, left/right, etc). Do not include?
Should background be part of window frame pieces or as is? Main window BG will need light color text. Sub-Window (a.k.a., window sections) BG will need dark text. Is this acceptable?
Are there any other buttons required that have not been mentioned in the list above?
Do we need a font or is system text sufficient?
Is there anything required that has not yet been mentioned above?

**Comment by seiyria** [comment]
I was debating about having slot art for each of the slots. If we do it for the hands, we'd have to do it for everything.

Background can be a part of the frame if it works.

Text colors are fine.

I can't think of anything.

System text is fine for a font.

Offhand I do not know, I haven't had a lot of time to review this as I've been crunching away in other parts of the project.

**Comment by cjepson1978** [comment]
![interface](https://user-images.githubusercontent.com/29284047/27812667-740acc6e-603e-11e7-8cab-b57a1fa33dc9.png)
Need review on updated work. Please see attached.

**Comment by seiyria** [comment]
A lot of it seems ok. The texture used for window backgrounds does not mesh very well. I can see the breaks between the texture.

**Comment by cjepson1978** [comment]
Updated, please provide feedback or request to submit PR if satisfied.
![interface](https://user-images.githubusercontent.com/29284047/27936888-3d8eb8fe-6281-11e7-8d9d-a1282b841354.png)

**Comment by seiyria** [comment]
This looks alright. It'll have to be integrated first so I'll leave this
open while I sort through the alpha issues. I'll get this in sometime in
the next couple weeks and let you know if anything is missing.

Thanks.

**Comment by cjepson1978** [comment]
Not needed.
